services:
  mongodb:
    image: mongo
    container_name: livestream_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: livestream_app
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - livestream-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis
    container_name: livestream_redis
    ports:
      - "6379:6379"
    networks:
      - livestream-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livestream_backend
    environment:
      - FLASK_CONFIG=production
      - MONGO_URI=mongodb://admin:password@mongodb:27017/livestream_app?authSource=admin
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:3000,http://localhost,http://client:80
      - SECRET_KEY=ashlok2003
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./hls_output:/app/hls_output
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - livestream-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/settings/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: livestream_client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - livestream-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:

networks:
  livestream-network:
    driver: bridge
